[build]
  command = "next build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18.19.1"
  NEXT_TELEMETRY_DISABLED = "1"
  # Environment flags
  NEXT_PUBLIC_DEPLOY_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://livesitemiz.netlify.app"
  # Debug logs
  DEBUG = "@netlify/next,netlify-next-plugin"

# Add dependency cache plugin
[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ]

# Production context
[context.production]
  command = "next build"
  publish = ".next"

# Deploy Preview context
[context.deploy-preview]
  command = "next build"
  publish = ".next"

# Handle Next.js routing - critical for proper path handling
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

# Properly handle dynamic routes
[[redirects]]
  from = "/admin/users/*"
  to = "/.netlify/functions/next"
  status = 200

[[redirects]]
  from = "/sifre-sifirlama/*"
  to = "/.netlify/functions/next"
  status = 200

# Single page app handling
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = false

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for HTML and data
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/data/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  # Configure functions to handle Next.js properly
  node_bundler = "esbuild"
  # List all the large dependencies that should be excluded from bundling
  external_node_modules = [
    "@netlify/next",
    "next",
    "react",
    "react-dom",
    "@next/font",
    "sharp",
    "@supabase/supabase-js",
    "@vercel/analytics",
    "tailwindcss",
    "postcss",
    "autoprefixer"
  ]
  # Increase the function timeout for better performance
  timeout = 30
  # Increase memory
  memory = 1024

[functions."next-*"]
  # Configuration specifically for the Next.js functions
  included_files = [".next/server/**"]
  external_node_modules = [
    "@netlify/next",
    "next",
    "react",
    "react-dom",
    "@next/font",
    "sharp",
    "@supabase/supabase-js",
    "@vercel/analytics",
    "tailwindcss",
    "postcss",
    "autoprefixer"
  ]
