[build]
  command = "node build-static.js"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18.19.1"
  NEXT_TELEMETRY_DISABLED = "1"
  # Force static export
  NETLIFY = "true"
  NEXT_EXPORT = "true"
  # Disable experimental features
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_ESLINT_DURING_BUILD = "true"
  # Skip running our custom plugins
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Environment flags
  NEXT_PUBLIC_DEPLOY_ENV = "production"

# Add dependency cache plugin
[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ]

# Production context
[context.production]
  command = "node build-static.js"
  publish = "out"

# Deploy Preview context
[context.deploy-preview]
  command = "node build-static.js"
  publish = "out"

# Handle Next.js routing - critical for proper path handling
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

# API mock redirects
[[redirects]]
  from = "/api/market/items"
  to = "/mocks/api/market-items.json"
  status = 200

[[redirects]]
  from = "/api/market/items/*"
  to = "/mocks/api/market-items.json"
  status = 200

[[redirects]]
  from = "/api/list-market-images"
  to = "/mocks/api/market-images.json"
  status = 200

[[redirects]]
  from = "/api/upload/market-images"
  to = "/mocks/api/upload-response.json"
  status = 200

[[redirects]]
  from = "/api/upload/market-images/*"
  to = "/mocks/api/upload-response.json"
  status = 200

# Single page app handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for HTML and data
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/data/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Ensure password reset routing works
[[redirects]]
  from = "/sifre-sifirlama/*"
  to = "/index.html"
  status = 200
